"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"preserve_hierarchy": true

"files": [
  {
    "source": "config/locales/**/en.yml",
    "translation": "config/locales/**/%two_letters_code%.yml"
  },
  {
    "source": "config/locales/*.en.yml",
    "translation": "config/locales/%original_file_name_without_en%.%two_letters_code%.yml"
  },
  {
    "source": "simulator/src/i18n/en.json",
    "translation": "simulator/src/i18n/%two_letters_code%.json"
  }
]
